name: tests

on:
  push:
    paths:
      - 'src/**.js'
  pull_request:
    paths:
      - 'src/**.js'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i &&  npm run test:ci && docker build -t mohsinwaseem65/ci .
      - run: docker login -u mohsinwaseem65 -p Mrvsk12678@wa
        env:
          $DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          $DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push mohsinwaseem65/ci
